export const CLICK_FOO = 'CLICK_FOO';

export const FETCH_SKILLS_INIT = 'FETCH_SKILLS_INIT';
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS';
export const FETCH_SKILLS_FAILURE = 'FETCH_SKILLS_FAILURE';

export const FETCH_SKILL_INIT = 'FETCH_SKILL_INIT';
export const FETCH_SKILL_SUCCESS = 'FETCH_SKILL_SUCCESS';
export const FETCH_SKILL_FAILURE = 'FETCH_SKILL_FAILURE';

export const ADD_SKILL_INIT = 'ADD_SKILL_INIT';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_FAILURE = 'ADD_SKILL_FAILURE';

export const UPDATE_SKILL_INIT = 'UPDATE_SKILL_INIT';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const UPDATE_SKILL_FAILURE = 'UPDATE_SKILL_FAILURE';
