export const CLICK_FOO = 'CLICK_FOO';
export const FETCH_SKILLS_INIT = 'FETCH_SKILLS_INIT';
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS';
export const FETCH_SKILLS_FAILURE = 'FETCH_SKILLS_FAILURE';

export const ADD_SKILL_INIT = 'ADD_SKILL_INIT';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_FAILURE = 'ADD_SKILL_FAILURE';
