export const CLICK_FOO = 'CLICK_FOO';
export const FETCH_SKILLS_INIT = 'FETCH_SKILLS_INIT';
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS';
export const FETCH_SKILLS_FAILURE = 'FETCH_SKILLS_FAILURE';
